### ISSUE TITLE
Extend libpe's API to support all the properties of PEV

### ISSUE THREAD

**Issue by boddumanohar** [merces/libpe#13] opened 2017-06-26 04:42 UTC
Currently libpe API supports "sections", "headers", "Directories". We need to add support for other properties of the PEV like "hashes", "Imports", "exports", "resources", "relocations", "entrophy".

**Comment by jweyrich** [comment] 2017-08-10 16:16
Merged in fd4cc8178479eeb89634979054519f1305da657f. Thank you!

**Closed by jweyrich** 2017-08-10 16:16 UTC
Labels: enhancement

**Comment by jweyrich** [comment] 2017-08-10 16:22
@boddumanohar we still need to find what's causing those memory warnings/errors detected by valgrind.
I suspect it's caused by a memory corruption somewhere (possibly an overflow) - but haven't had the time to investigate yet.
